development:
  adapter: postgresql
  encoding: unicode
  database: workshop_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: workshop_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: workshop
  pool: 5
  username:
  password: